name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t spic/docker-react-udemy -f Dockerfile.dev .
      - run: docker run -e CI=true spic/docker-react-udemy npm test -- --coverage

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

  build_and_deploy_to_ebs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Upload to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: spicreactudemy
          environment_name: Spicreactudemy-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-761478465753
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip